// Prints the device attributes that matter for kernel design and for the
// "is this feature on GeForce?" questions (persisting L2, compression, clusters...).
#include "common.h"

#define A(x) {x, #x}
static const struct {
    CUdevice_attribute a;
    const char *n;
} k_attrs[] = {
    A(CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR),
    A(CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR),
    A(CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT),
    A(CU_DEVICE_ATTRIBUTE_CLOCK_RATE),
    A(CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE),
    A(CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH),
    A(CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE),
    A(CU_DEVICE_ATTRIBUTE_MAX_PERSISTING_L2_CACHE_SIZE),
    A(CU_DEVICE_ATTRIBUTE_MAX_ACCESS_POLICY_WINDOW_SIZE),
    A(CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK),
    A(CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR),
    A(CU_DEVICE_ATTRIBUTE_MAX_BLOCKS_PER_MULTIPROCESSOR),
    A(CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK),
    A(CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR),
    A(CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK),
    A(CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN),
    A(CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR),
    A(CU_DEVICE_ATTRIBUTE_RESERVED_SHARED_MEMORY_PER_BLOCK),
    A(CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY),
    A(CU_DEVICE_ATTRIBUTE_WARP_SIZE),
    A(CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT),
    A(CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS),
    A(CU_DEVICE_ATTRIBUTE_GENERIC_COMPRESSION_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_CLUSTER_LAUNCH),
    A(CU_DEVICE_ATTRIBUTE_MEM_SYNC_DOMAIN_COUNT),
    A(CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS),
    A(CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES),
    A(CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS),
    A(CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST),
    A(CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM),
    A(CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_ONLY_PARTIAL_HOST_NATIVE_ATOMIC_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_DMA_BUF_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_HOST_ALLOC_DMA_BUF_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_SPARSE_CUDA_ARRAY_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_DEFERRED_MAPPING_CUDA_ARRAY_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH),
    A(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS),
    A(CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT),
    A(CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT),
    A(CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT),
    A(CU_DEVICE_ATTRIBUTE_TIMELINE_SEMAPHORE_INTEROP_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_TENSOR_MAP_ACCESS_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_IPC_EVENT_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_NUMA_CONFIG),
    A(CU_DEVICE_ATTRIBUTE_MPS_ENABLED),
    A(CU_DEVICE_ATTRIBUTE_HOST_NUMA_ID),
    A(CU_DEVICE_ATTRIBUTE_GPU_PCI_DEVICE_ID),
    A(CU_DEVICE_ATTRIBUTE_PCI_BUS_ID),
    A(CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO),
    A(CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED),
    A(CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH),
    A(CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT),
    A(CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING),
    A(CU_DEVICE_ATTRIBUTE_ECC_ENABLED),
};

int cmd_attrs(int argc, char **argv) {
    (void)argc;
    (void)argv;
    char name[256];
    CK(cuDeviceGetName(name, sizeof name, g_dev));
    size_t total;
    CK(cuDeviceTotalMem(&total, g_dev));
    int drv;
    CK(cuDriverGetVersion(&drv));
    printf("device            %s\n", name);
    printf("total memory      %.2f GiB\n", total / 1073741824.0);
    printf("driver API        %d\n", drv);
    for (size_t i = 0; i < sizeof k_attrs / sizeof k_attrs[0]; i++) {
        int v = -999;
        CUresult r = cuDeviceGetAttribute(&v, k_attrs[i].a, g_dev);
        if (r != CUDA_SUCCESS)
            printf("%-66s (error %d)\n", k_attrs[i].n + 20, (int)r);
        else
            printf("%-66s %d\n", k_attrs[i].n + 20, v);
    }
    // Green-context SM resource: how finely can the SMs be partitioned?
    CUdevResource res;
    if (cuDeviceGetDevResource(g_dev, &res, CU_DEV_RESOURCE_TYPE_SM) == CUDA_SUCCESS) {
        printf("green ctx SM resource: smCount=%u minSmPartitionSize=%u smCoscheduledAlignment=%u\n",
               res.sm.smCount, res.sm.minSmPartitionSize, res.sm.smCoscheduledAlignment);
    }
    size_t free_b, tot_b;
    CK(cuMemGetInfo(&free_b, &tot_b));
    printf("free now          %.2f GiB\n", free_b / 1073741824.0);
    return 0;
}
